excluded:
  - GolfPadTestProblem/Code/App/AppDelegate.swift
  - GolfPadTestProblem/Code/App/SceneDelegate.swift
  - GolfPadTestProblem/Code/Extension/Combine + UIControl.swift

disabled_rules:
   - identifier_name
